name: Model Calibration on Push

on:
  push:
    branches:
      - main

jobs:
  calibrate-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn joblib

      - name: Calibrate latest model
        run: |
          echo "⚙️ Calibrating latest Logistic Regression model..."
          latest_model=$(ls models/model_*_lr_model.joblib | sort | tail -n 1)
          echo "Found latest model: $latest_model"

          python - <<'EOF'
          import joblib, os
          from sklearn.calibration import CalibratedClassifierCV
          from sklearn.datasets import make_classification
          import numpy as np
          from datetime import datetime

          model_path = sorted([f for f in os.listdir("models") if f.endswith("_lr_model.joblib")])[-1]
          model = joblib.load(os.path.join("models", model_path))

          # Create synthetic calibration data
          X_cal, y_cal = make_classification(
              n_samples=800, n_features=6, n_informative=3, n_classes=2, random_state=123
          )

          calibrated_model = CalibratedClassifierCV(model, method='sigmoid', cv=3)
          calibrated_model.fit(X_cal, y_cal)

          timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
          calibrated_name = f"model_{timestamp}_calibrated_lr_model.joblib"
          joblib.dump(calibrated_model, os.path.join("models", calibrated_name))
          print(f"✅ Calibrated model saved as: {calibrated_name}")
          EOF

      - name: Commit and push calibrated model
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add models/
          git commit -m "🤖 Added calibrated Logistic Regression model"
          git push

